test-fru-utils: fix clang-tidy error
clang-tidy-19 suggests making a trivial reserve call due to a sequence
of push_back calls in the test case.  Add as directed.

```
../test/test_fru-utils.cpp:173:9: error: 'push_back' is called inside a loop; consider pre-allocating the container capacity before the loop [performance-inefficient-vector-operation,-warnings-as-errors]
```

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ia453674492b0ca5fb3b56fd2bf5326b3c1ca7f86