test: missing dependency on sdbusplus
It was reported that there are test case failures in CI on EM:

/usr/bin/ld: test_fru_utils.p/src_Utils.cpp.o:(.data.rel.local.DW.ref._ZTIN9sdbusplus9exception10SdBusErrorE[DW.ref._ZTIN9sdbusplus9exception10SdBusErrorE]+0x0): undefined reference to `typeinfo for sdbusplus::exception::SdBusError'

This is due to a missing dependency.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I0cc51385fd87ba5ba2bb84a5a889e4c633f11e74