meson: remove broken fru-device-resizefru option
This is apparently unused, as it has been broken for some time with the
following errors:

```
FAILED: src/fru-device.p/fru_device.cpp.o
ccache c++ -Isrc/fru-device.p -I../include -I/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++20 -O0 -g -Wno-psabi -pthread -DBOOST_ASIO_DISABLE_THREADS -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -isystem../subprojects/valijson/include -isystem../subprojects/sdbusplus/include -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_NO_RTTI -DBOOST_NO_TYPEID -DBOOST_ALL_NO_LIB -DBOOST_ALLOW_DEPRECATED_HEADERS '-DPACKAGE_DIR="/usr/local/share/entity-manager/"' '-DSYSCONF_DIR="/usr/local/etc/entity-manager/"' -DENABLE_FRU_AREA_RESIZE -MD -MQ src/fru-device.p/fru_device.cpp.o -MF src/fru-device.p/fru_device.cpp.o.d -o src/fru-device.p/fru_device.cpp.o -c ../src/fru_device.cpp
../src/fru_device.cpp: In function ‘bool updateFRUProperty(const std::string&, uint32_t, uint32_t, const std::string&, boost::container::flat_map<std::pair<long unsigned int, long unsigned int>, std::shared_ptr<sdbusplus::asio::dbus_interface> >&, size_t&, const bool&, sdbusplus::asio::object_server&, std::shared_ptr<sdbusplus::asio::connection>
&)’:
../src/fru_device.cpp:1225:28: error: ‘fruAreaInternal’ was not declared in this scope; did you mean ‘fruAreas::fruAreaInternal’?
 1225 |         for (int fruArea = fruAreaInternal; fruArea <= fruAreaMultirecord;
      |                            ^~~~~~~~~~~~~~~
      |                            fruAreas::fruAreaInternal
In file included from ../src/fru_device.cpp:18:
../include/fru_utils.hpp:58:5: note: ‘fruAreas::fruAreaInternal’ declared here
   58 |     fruAreaInternal = 0,
      |     ^~~~~~~~~~~~~~~
../src/fru_device.cpp:1225:56: error: ‘fruAreaMultirecord’ was not declared in this scope; did you mean ‘fruAreas::fruAreaMultirecord’?
 1225 |         for (int fruArea = fruAreaInternal; fruArea <= fruAreaMultirecord;
      |                                                        ^~~~~~~~~~~~~~~~~~
      |                                                        fruAreas::fruAreaMultirecord
../include/fru_utils.hpp:62:5: note: ‘fruAreas::fruAreaMultirecord’ declared here
   62 |     fruAreaMultirecord
      |     ^~~~~~~~~~~~~~~~~~
../src/fru_device.cpp:1228:72: error: cannot convert ‘int’ to ‘fruAreas’
 1228 |             unsigned int fruAreaOffsetField = getHeaderAreaFieldOffset(fruArea);
      |                                                                        ^~~~~~~
      |                                                                        |
      |                                                                        int
../include/fru_utils.hpp:167:48: note:   initializing argument 1 of ‘unsigned int getHeaderAreaFieldOffset(fruAreas)’
  167 | unsigned int getHeaderAreaFieldOffset(fruAreas area);
      |                                       ~~~~~~~~~^~~~
../src/fru_device.cpp:1230:36: error: ‘fruAreaOffsetFieldValue’ was not declared in this scope; did you mean ‘fruAreaOffsetField’?
 1230 |             if (curFRUAreaOffset > fruAreaOffsetFieldValue)
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
      |                                    fruAreaOffsetField
```

This was at least influenced by the refactor in bdfc5ec6932c ("Add a
helper function findFruAreaLocationAndField to updateFRUProperty") which
introduced the error at ../src/fru_device.cpp:1230:36, the remaining
errors come from a time before I could be bothered to find via
bisection, though 9f0f2d114468 ("FruDevice: use FRU Areas enum to
iterate") seems likely.

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: I31af64ab3f4a1741947cd0272e6c04e3e37a0a05