fru-device: Add sdbusplus dependency for test
Fix the following build error:

```
FAILED: test_fru_utils.p/src_fru_utils.cpp.o
ccache c++ -Itest_fru_utils.p -I../include -I../subprojects/gtest/googletest/include -I../subprojects/gtest/googletest -Isubprojects/gtest/__CMake_build -I../subprojects/gtest/__CMake_build -Isubprojects/gtest -I../subprojects/gtest -I/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -W
pedantic -Werror -std=c++20 -O0 -g -Wno-psabi -pthread -isystem../subprojects/gtest/googletest -isystem../subprojects/gtest/googletest/include -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_NO_RTTI -DBOOST_NO_TYPEID -DBOOST_ALL_NO_LIB -DBOOST_ALLOW_DEPRECATED_HEADERS -DBOOST_ASIO_DISABLE_THREADS -MD -MQ test_fru_utils.p/src_
fru_utils.cpp.o -MF test_fru_utils.p/src_fru_utils.cpp.o.d -o test_fru_utils.p/src_fru_utils.cpp.o -c ../src/fru_utils.cpp
In file included from ../src/fru_utils.cpp:18:
../include/fru_utils.hpp:22:10: fatal error: sdbusplus/asio/object_server.hpp: No such file or directory
   22 | #include <sdbusplus/asio/object_server.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/7] Compiling C++ object test_fru_utils.p/test_test_fru-utils.cpp.o
FAILED: test_fru_utils.p/test_test_fru-utils.cpp.o
ccache c++ -Itest_fru_utils.p -I../include -I../subprojects/gtest/googletest/include -I../subprojects/gtest/googletest -Isubprojects/gtest/__CMake_build -I../subprojects/gtest/__CMake_build -Isubprojects/gtest -I../subprojects/gtest -I/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -W
pedantic -Werror -std=c++20 -O0 -g -Wno-psabi -pthread -isystem../subprojects/gtest/googletest -isystem../subprojects/gtest/googletest/include -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_NO_RTTI -DBOOST_NO_TYPEID -DBOOST_ALL_NO_LIB -DBOOST_ALLOW_DEPRECATED_HEADERS -DBOOST_ASIO_DISABLE_THREADS -MD -MQ test_fru_utils.p/test
_test_fru-utils.cpp.o -MF test_fru_utils.p/test_test_fru-utils.cpp.o.d -o test_fru_utils.p/test_test_fru-utils.cpp.o -c ../test/test_fru-utils.cpp
In file included from ../test/test_fru-utils.cpp:1:
../include/fru_utils.hpp:22:10: fatal error: sdbusplus/asio/object_server.hpp: No such file or directory
   22 | #include <sdbusplus/asio/object_server.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[5/7] Compiling C++ object src/fru-device.p/fru_device.cpp.o
ninja: build stopped: subcommand failed.
```

gitlint-ignore: body-max-line-length,body-max-line-length-with-exceptions
Fixes: d79d02516fcc ("Refactor : Add a helper function findIndexForFRU to addFruObjectToDbus")
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: If453423a8efb53700a15197e46a404920d81578a