fix ci build
Properly define the libgpiod version we depend on (sorry).

The default seems to have changed in our CI container.

The compiler used also seems to have trouble with combined destructuring
assignment and coroutines.

```
C++ compiler for the host machine: c++ (gcc 15.0.1 "c++ (Ubuntu 15-20250404-0ubuntu1) 15.0.1 20250404 (experimental) [master r15-9193-g08e803aa9be]")
```

```
../src/gpio-presence/config_provider.cpp: In function ‘void gpio_presence::ConfigProvider::handleInterfacesAdded(_ZN13gpio_presence14ConfigProvider21handleInterfacesAddedESt8functionIFvRKN9sdbusplus7message7details19string_path_wrapperEEE.Frame*)’:
../src/gpio-presence/config_provider.cpp:120:5: error: ‘<anonymous>’ may be used uninitialized [-Werror=maybe-uninitialized]
  120 |     }
      |     ^
../src/gpio-presence/config_provider.cpp:103:68: note: ‘<anonymous>’ was declared here
  103 |                 .next<sdbusplus::message::object_path, ConfigData>();
      |                                                                    ^
```

Apply the band-aid of using a local variable then destructure later.

Tested: Inspection only.

Change-Id: I314d3ee241afe963f730f4c3978fb8f467a2913a
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>