fix performance-prefer-single-char-overloads
```
error: 'performance-faster-string-find' check is deprecated and will be removed in a future release; consider using 'performance-prefer-single-char-overloads' instead [clang-tidy-config,-warnings-as-errors]
../src/fru_device/fru_device.cpp:903:24: error: 'operator+=' called with a string literal consisting of a single character; consider using the more efficient overload accepting a character [performance-faster-string-find,-warnings-as-errors]
  903 |         productName += "_";
      |                        ^~~
      |
```

fix the issue found by clang-tidy and migrate the check [1], [2].

According to [1] the check is an alias for [2] so there should be no
change in our tidy coverage.

References:
[1] https://clang.llvm.org/extra/clang-tidy/checks/performance/faster-string-find.html
[2] https://clang.llvm.org/extra//clang-tidy/checks/performance/prefer-single-char-overloads.html

Change-Id: I2bb87611adf11eabeb66e0f352d6edf97b0a6f08
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>