Fix sign compare issues in unit tests
On some version of gtest, the following warning is seen.

```
../test/test_topology.cpp:71:5:   required from here
/usr/src/googletest/googletest/include/gtest/gtest.h:1379:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
 1379 |   if (lhs == rhs) {
```

Fix the warning by making integer comparisons unsigned.

Change-Id: Idf0b5b675f0579898e58aa27ceb558f5edcc91b2
Signed-off-by: Ed Tanous <etanous@nvidia.com>