fru-device: value initialize 'ipmiFruBlock'
clang-tidy warned about this in a CI log of an unrelated change [1]
which does not even modify this code.

```
../src/fru_device/fru_utils.hpp:131:8: error: constructor does not initialize these fields: ipmiFruBlock [cppcoreguidelines-pro-type-member-init,-warnings-as-errors]
  131 | struct FruSections
      |        ^
  132 | {
  133 |     off_t IpmiFruOffset = 0;
  134 |     std::array<uint8_t, I2C_SMBUS_BLOCK_MAX> ipmiFruBlock;
      |
      |                                                          {}
```

clang-tidy recommends value initialization [2], apply it here.

Tested: Inspection only.

References:

[1] https://gerrit.openbmc.org/c/openbmc/entity-manager/+/93253
[2] https://en.cppreference.com/cpp/language/value_initialization

Change-Id: Ib5070df75a9055c536d09972297bd6f46b007eec
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>